web_jinja/routes.py
#!/usr/bin/python3
""" Starts a Flash Web Application """
import base64
import requests
import models
from flask import current_app
from datetime import datetime
from flask import flash
from flask import session
from flask import Blueprint, render_template, request, redirect, url_for, abort
from flask_login import current_user
from flask_login import login_user, login_required, logout_user, LoginManager
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from models.engine.db_storage import DBStorage
from models.user import User
import os
from .forms import CreateEventForm
from models.reservation import Reservation
from models.review import Review
from models.event import Event
from flask_wtf import csrf
from werkzeug.utils import secure_filename

storage = DBStorage()
storage.reload()

routes_bp = Blueprint('routes', __name__)

from app import login_manager
@login_manager.user_loader
def load_user(user_id):
    """Loads the user object based on the user_id"""
    return storage.get(User, user_id)

@login_manager.unauthorized_handler
def unauthorized():
    flash('Please sign in to access this page.', 'error')
    return redirect(url_for('routes.signin'))

class SigninForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Sign In')

@routes_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    """signup method"""
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        password = request.form.get('password')

        user = User(name=name, email=email, password=password)
        storage.new(user)
        storage.save()

        return redirect(url_for('routes.signin'))

    return render_template('signup.html')

@routes_bp.route('/signin', methods=['GET', 'POST'])
def signin():
    """signin method"""
    form = SigninForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        users = storage.all(User)
        user = next((user for user in users.values() if user.email == email), None)

        if user and user.validate_password(password):
            session['user_id'] = user.id
            login_user(user)
            return redirect(url_for('routes.profile'))
        else:
            flash('Invalid email or password', 'error')

    return render_template('signin.html', form=form)


def get_current_user():
    """Get current user"""
    user_id = session.get('user_id')
    if user_id:
        return storage.get(User, user_id)
    return None

@routes_bp.route('/create_event', methods=['GET', 'POST'])
@login_required
def create_event():
    """ Creating event"""
    if not current_user.is_authenticated:
        return redirect(url_for('routes.signin'))

    form = CreateEventForm()
    csrf_token = csrf.generate_csrf()

    if form.validate_on_submit():
        title = form.title.data
        description = form.description.data
        image_file = form.image.data
        venue = form.venue.data
        date_time = form.date_time.data
        slots_available = form.slots_available.data

        event = None

        if image_file:
            filename = secure_filename(image_file.filename)
            filepath = os.path.join('web_jinja/static/images/', filename)
            image_file.save(filepath)

            with open(filepath, 'rb') as f:
                image_data = f.read()

            encoded_image = base64.b64encode(image_data).decode('utf-8')

            event = Event(
                title=title,
                description=description,
                image_file=filepath,
                venue=venue,
                date_time=date_time,
                slots_available=slots_available,
                user=current_user._get_current_object()
            )
        else:
            event = Event(
                title=title,
                description=description,
                venue=venue,
                date_time=date_time,
                slots_available=slots_available,
                user=current_user._get_current_object()
            )
        storage.new(event)
        storage.save()
        return redirect(url_for('routes.profile'))
    else:

        return render_template('create_event.html', form=form)

@routes_bp.route('/event/<event_id>')
def view_event(event_id):
    """Retrieve the event from the API using the event_id"""
    response = requests.get(f'https://portfolioproject-production-496e.up.railway.app/api/v1/events/{event_id}')
    if response.status_code == 200:
        event = response.json()
        event['has_passed'] = datetime.strptime(event['date_time'], '%Y-%m-%dT%H:%M:%S') < datetime.now()
        reviews_response = requests.get(f'https://portfolioproject-production-496e.up.railway.app/api/v1/events/{event_id}/reviews')
        if reviews_response.status_code == 200:
            reviews = reviews_response.json()
            event['reviews'] = reviews
        else:
            event['reviews'] = []

        return render_template('event_page.html', event=event)
    else:
        return render_template('error.html', message='Failed to retrieve event')

@routes_bp.route('/')
def home():
    """Retrieve events from the API"""
    response = requests.get('https://portfolioproject-production-496e.up.railway.app/api/v1/events')
    if response.status_code == 200:
        events = response.json()
        for event in events:
            if event['image'] is not None:
                event['image_path'] = '/static/images/' + event['image']
            else:
                event['image_path'] = '/static/images/default.jpg'
            event['has_passed'] = datetime.strptime(event['date_time'], '%Y-%m-%dT%H:%M:%S') < datetime.now()
        return render_template('home.html', events=events)
    else:
        return render_template('error.html', message='Failed to retrieve events')

@routes_bp.route('/events/<event_id>/review', methods=['GET', 'POST'])
@login_required
def review_event(event_id):
    """Review event"""
    if not current_user.is_authenticated:
        return redirect(url_for('routes.signin'))

    if request.method == 'POST':
        content = request.form.get('content')
        if content:
            user_id = current_user.id
            review = Review(content=content, event_id=event_id, user_id=user_id)
            storage.new(review)
            storage.save()
            flash('Review submitted successfully!')
            return redirect(url_for('routes.view_event', event_id=event_id))
        else:
            flash('Please enter a review before submitting.')

    event = storage.get(Event, event_id)
    if not event:
        abort(404)

    return render_template('review.html', event=event)

@routes_bp.route('/reserve', methods=['POST'])
@login_required
def reserve_event():
    """Function that reserves a slot for a user"""
    if not current_user.is_authenticated:
        return redirect(url_for('routes.signin'))

    user_id = current_user.id

    event_id = request.form.get('event_id')

    event = storage.get(Event, event_id)

    if event:
        if event.slots_available > 0:
            slots_reserved = 1
            reservation = Reservation(user_id=user_id, event_id=event_id,
                                      slots_reserved=slots_reserved)
            storage.new(reservation)
            storage.save()
            event = storage.session.merge(event)
            event.slots_available -= slots_reserved
            storage.save()
            return redirect(f'/event/{event_id}')
        else:
            return render_template('error.html', message='No slots available')
    else:
        return render_template('error.html', message='Failed to retrieve event')

@routes_bp.route("/search", methods=["GET"])
def search_events():
    """Searches events based on title and venue"""
    query = request.args.get("query", "").lower()
    results = []

    if query:
        events = models.storage.all(Event).values()
        results = [event for event in events if query in getattr(event, "title", "").lower() or query in getattr(event, "venue", "").lower()]

    return render_template("search_results.html", results=results)

@routes_bp.route('/profile')
@login_required
def profile():
    """profile display"""
    if not current_user.is_authenticated:
        return redirect(url_for('routes.signin'))

    user = current_user

    if user:
        return render_template('profile.html', user=user)

    return redirect('/signin')

@routes_bp.route('/signout')
@login_required
def signout():
    """signout function"""
    if not current_user.is_authenticated:
        return redirect(url_for('routes.signin'))

    session.pop('user_id', None)
    return redirect('/signin')

web_jinja/templates/base.html
<html>
  <head>
    <title>{% block title %}Events Hub{% endblock %}</title>
    <!-- Add necessary CSS files for social media icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <style>
      /* CSS styles for the header navigation */
      header {
        display: flex;
        justify-content: space-between; /* Add space between search form and navigation buttons */
        align-items: center; /* Vertically center-align the content */
        padding: 10px;
      }

      /* CSS styles for the navigation buttons */
      nav ul {
        list-style: none;
        display: flex;
        gap: 10px; /* Add spacing between buttons */
      }

      nav ul li {
        display: flex;
      }

      nav ul li a {
        display: inline-block;
        padding: 10px 20px;
        background-color: #f44336;
        color: white;
        text-decoration: none;
        border-radius: 5px;
      }

      /* CSS styles for the search form section */
      .search-section {
        margin-top: 10px; /* Add margin top to create space below the navigation section */
        display: flex;
        justify-content: space-between; /* Add space between search form and logo */
        align-items: center; /* Vertically center-align the content */
      }

      /* CSS styles for the search form */
      form {
        display: flex;
        align-items: center; /* Vertically center-align the form */
      }

      input[type="text"] {
        margin-right: 10px; /* Add space between input field and button */
      }

      /* CSS styles for the footer */
      footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        background-color: #f5f5f5;
        padding: 20px 0;
        text-align: center; /* Center-align the content */
      }

      .social-media {
        margin-top: 10px;
      }

      /* Set a minimum height for the main content */
      main {
        min-height: calc(100vh - 130px); /* Subtract the height of the header and footer */
      }

      /* CSS styles for the site logo */
      .site-logo {
        font-size: 30px;
        font-weight: bold;
        color: black;
        text-decoration: none;
        border-bottom: none; /* Remove the line under the logo */
      }
      
      .site-logo a {
        display: flex;
        align-items: center;
        text-decoration: none; /* Remove the underline */
      }

    </style>
  </head>
  <body>
    <header>
      <!-- Your header content goes here -->
      <h1 class="site-logo"><a href="/">Events Hub</a></h1>
      <nav>
        <ul>
          <li><a href="/">Home</a></li>
          <li><a href="https://isaaccleopas.wixsite.com/events-hub/about-1">About</a></li>
          <li><a href="/create_event">Create Event</a></li>
        </ul>
      </nav>
    </header>

    <section class="search-section">
      <form action="/search" method="GET">
        <input type="text" name="query" placeholder="Search by location or event title">
        <button type="submit">Search</button>
      </form>
    </section>

    <main>
      {% block content %}
      {% endblock %}
    </main>

    <footer>
      <p>&copy; {{ current_year }} Events Hub. All rights reserved.</p>
      <div class="social-media">
        <a href="https://twitter.com/ILawnar" target="_blank"><i class="fab fa-twitter"></i></a>
        <a href="https://github.com/isaaccleopas" target="_blank"><i class="fab fa-github"></i></a>
        <a href="https://www.linkedin.com/in/isaac-cleopas-lawnar-2aa88b151/" target="_blank"><i class="fab fa-linkedin"></i></a>
      </div>
    </footer>

    <!-- Add necessary JavaScript files for social media icons -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"></script>
  </body>
</html>

web_jinja/templates/create_event.html
{% extends 'base.html' %}

{% block content %}
  <h1>Create Event</h1>
  <form method="POST" action="{{ url_for('routes.create_event') }}" enctype="multipart/form-data">
    {{ form.csrf_token }}

    {{ form.title.label }}
    {{ form.title() }}
    {% if form.title.errors %}
      <ul class="errors">
        {% for error in form.title.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    {{ form.description.label }}
    {{ form.description() }}
    {% if form.description.errors %}
      <ul class="errors">
        {% for error in form.description.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    {{ form.image.label }}
    {{ form.image() }}
    {% if form.image.errors %}
      <ul class="errors">
        {% for error in form.image.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    {{ form.venue.label }}
    {{ form.venue() }}
    {% if form.venue.errors %}
      <ul class="errors">
        {% for error in form.venue.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    {{ form.date_time.label }}
    {{ form.date_time() }}
    {% if form.date_time.errors %}
      <ul class="errors">
        {% for error in form.date_time.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    {{ form.slots_available.label }}
    {{ form.slots_available() }}
    {% if form.slots_available.errors %}
      <ul class="errors">
        {% for error in form.slots_available.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    <button type="submit">Submit</button>
  </form>
{% endblock %}

web_jinja/templates/error.html
<!DOCTYPE html>
<html>
  <head>
    <title>Error</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f2f2f2;
        padding: 20px;
      }

      h1 {
        color: #ff0000;
        font-size: 24px;
      }

      p {
        font-size: 16px;
      }
    </style>
  </head>
  <body>
    <h1>Error</h1>
    <p>{{ message }}</p>
  </body>
</html>

web_jinja/templates/event_page.html
{% extends 'base.html' %}

{% block content %}
  <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; height: 100vh; text-align: center;">
    {% if event.image %}
      <img src="{{ url_for('static', filename='images/' + event.image) }}" alt="Event Image">
    {% else %}
      <img src="{{ url_for('static', filename='default.png') }}" alt="Default Event Image">
    {% endif %}
    <h1>{{ event.title }}</h1>
    <p>Date and Time: {{ event.date_time }}</p>
    <p>Venue: {{ event.venue }}</p>
    <p>Slots Available: {{ event.slots_available }}</p>
    <p>Description: {{ event.description }}</p>

    {% if event.has_passed %}
      <a href="/events/{{ event.id }}/review">Review</a>
    {% else %}
      {% if event.slots_available > 0 %}
        <form action="/reserve" method="POST">
          <input type="hidden" name="event_id" value="{{ event.id }}">
          <button type="submit" class="reserve-btn">Reserve</button>
        </form>
      {% else %}
        <p>No slots available</p>
      {% endif %}
    {% endif %}

    <hr>

    {% if event.reviews %}
      <h1>Reviews</h1>
      <ul>
        {% for review in event.reviews %}
          <li>
            <p>Content: {{ review.content }}</p>
            <p>Date and Time: {{ review.created_at }}</p>
            <p>User: {{ review.user.name }}</p>
          </li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
{% endblock %}

web_jinja/templates/events.html
<!DOCTYPE html>
<html>
<head>
  <title>Event Grid</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
  <div class="event-grid">
    {% for event in events %}
      <div class="event-item">
        <a href="/event/{{ event.id }}">
          <div class="event-content">
            <div class="event-image">
              {% if event.image %}
                <img src="{{ url_for('static', filename='images/' + event.image) }}" alt="Event Image">
              {% else %}
                <img src="{{ url_for('static', filename='images/default.jpg') }}" alt="Default Event Image">
              {% endif %}
            </div>
            <div class="event-details">
              <h3>{{ event.title }}</h3>
              <p>Date: {{ event.date_time }}</p>
              <p>Location: {{ event.venue }}</p>
              {% if event.has_passed %}
                <a href="/events/{{ event.id }}/review">Review</a>
              {% else %}
                <form action="/reserve" method="POST">
                  <input type="hidden" name="event_id" value="{{ event.id }}">
                  <button type="submit" class="reserve-btn">Reserve</button>
                </form>
              {% endif %}
            </div>
          </div>
        </a>
      </div>
      {% if loop.index % 3 == 0 %}
        <div class="clear"></div>
      {% endif %}
    {% endfor %}
  </div>
</body>
</html>

web_jinja/templates/home.html
<!-- home.html -->
{% extends 'base.html' %}

{% block title %}Event Grid{% endblock %}

{% block content %}
  <style>
    .event-grid-container {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
      grid-gap: 20px;
      justify-items: center; /* Center-align the grid items horizontally */
      align-items: center; /* Center-align the grid items vertically */
    }
  </style>

  <div class="event-grid-container">
    {% for event in events %}
      <div class="event-item">
            <div class="event-image">
              {% if event.image %}
                <img src="{{ url_for('static', filename='images/' + event.image) }}" alt="Event Image">
              {% else %}
                <img src="{{ url_for('static', filename='default.png') }}" alt="Default Event Image">
              {% endif %}
            </div>
            <a href="/event/{{ event.id }}">
            <div class="event-content">
            <div class="event-details">
              <h3>{{ event.title }}</h3>
              <p>Date: {{ event.date_time }}</p>
              <p>Location: {{ event.venue }}</p>
              {% if event.has_passed %}
                <a href="/events/{{ event.id }}/review">Review</a>
              {% else %}
                <form action="/reserve" method="POST">
                  <input type="hidden" name="event_id" value="{{ event.id }}">
                  <button type="submit" class="reserve-btn">Reserve</button>
                </form>
              {% endif %}
            </div>
          </a>
          </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

web_jinja/templates/profile.html
<!-- profile.html -->
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
  <div style="display: flex; flex-direction: column; justify-content: space-between; height: 100vh; align-items: center;">
    <h1>Welcome, {{ user.name }}</h1>
    <p>Email: {{ user.email }}</p>
    <a href="/signout">Sign Out</a>
    <br>
    <a href="/create_event">Create Event</a>
    <br>
    <a href="/">Display Events</a>
  </div>
{% endblock %}

web_jinja/templates/review.html
{% extends 'base.html' %}

{% block content %}
  <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; height: 100vh; text-align: center;">
    <h1>Review Event</h1>
    <form style="margin-top: 20px;" method="POST" action="{{ url_for('routes.review_event', event_id=event.id) }}">
      <div style="margin-bottom: 10px;">
        <label for="content">Your Review:</label>
        <textarea id="content" name="content" rows="5" required></textarea>
      </div>
      <div>
        <button type="submit">Submit Review</button>
      </div>
    </form>
  </div>
{% endblock %}

web_jinja/templates/search_results.html
{% extends 'base.html' %}

{% block content %}
  <h2>Search Results for "{{ query }}"</h2>

  {% if results %}
    <ul>
      {% for event in results %}
        <li>
          <div style="display: flex; flex-direction: column; justify-content: center; align-items: center;">
            {% if event.image %}
              <img src="{{ url_for('static', filename='images/' + event.image) }}" alt="Event Image">
            {% else %}
              <img src="{{ url_for('static', filename='default.png') }}" alt="Default Event Image">
            {% endif %}
            <h3>{{ event.title }}</h3>
            <p>Date and Time: {{ event.date_time }}</p>
            <p>Venue: {{ event.venue }}</p>
            <p>Slots Available: {{ event.slots_available }}</p>
            <p>Description: {{ event.description }}</p>

            {% if event.has_passed %}
              <a href="/events/{{ event.id }}/review">Review</a>
            {% else %}
              {% if event.slots_available > 0 %}
                <form action="/reserve" method="POST">
                  <input type="hidden" name="event_id" value="{{ event.id }}">
                  <button type="submit" class="reserve-btn">Reserve</button>
                </form>
              {% else %}
                <p>No slots available</p>
              {% endif %}
            {% endif %}

            <hr>

            {% if event.reviews %}
              <h1>Reviews</h1>
              <ul>
                {% for review in event.reviews %}
                  <li>
                    <p>Content: {{ review.content }}</p>
                    <p>Date and Time: {{ review.created_at }}</p>
                    <p>User: {{ review.user.name }}</p>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </div>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No results found for "{{ query }}"</p>
  {% endif %}
{% endblock %}

web_jinja/templates/signin.html
{% extends 'base.html' %}

{% block title %}Signin{% endblock %}

{% block content %}
  <div style="text-align: center;">
    <h1>Signin</h1>
    <form method="POST" action="{{ url_for('routes.signin') }}">
      {{ form.csrf_token }}
      <label for="email">Email:</label>
      {{ form.email(class="form-control") }}
      <br>
      <label for="password">Password:</label>
      {{ form.password(class="form-control") }}
      <br>
      {{ form.submit(class="btn btn-primary btn-nav") }}
    </form>
    <p>Don't have an account? <a href="/signup">Signup</a></p>
  </div>
{% endblock %}

<style>
  .btn-nav {
    background-color: #f44336;
    color: white;
  }
</style>

web_jinja/templates/signup.html
{% extends 'base.html' %}

{% block title %}Signup{% endblock %}

{% block content %}
  <div style="text-align: center;">
    <h1>Signup</h1>
    <form method="POST" action="{{ url_for('routes.signup') }}">
      <label for="name">Name:</label>
      <input type="text" id="name" name="name" required>
      <br>
      <label for="email">Email:</label>
      <input type="email" id="email" name="email" required>
      <br>
      <label for="password">Password:</label>
      <input type="password" id="password" name="password" required>
      <br>
      <input type="submit" value="Signup" class="btn btn-primary btn-nav">
    </form>
    <p>Already have an account? <a href="/signin">Sign In</a></p>
  </div>
{% endblock %}

<style>
  .btn-nav {
    background-color: #f44336;
    color: white;
  }
</style>